### ISSUE TITLE
what will be the path in /path/to/flat/data

### ISSUE THREAD

**Issue by faisalpathan** [nguyenhuyanhh/nlp_speech#1]
The command to load the data in python "Import data: $ python data.py -i /path/to/flat/data" , here i am providing a path of the '.wav' file but it says
Traceback (most recent call last):
  File "data.py", line 196, in <module>
    import_folder(sys.argv[2])
  File "data.py", line 44, in import_folder
    for file_ in os.listdir(path):
OSError: [Errno 20] Not a directory: 'data/InboundSampleRecording.wav'

**Comment by nguyenhuyanhh** [comment]
Hello! path/to/flat/data must be a folder containing all the wav files.

So for your example, `.../data` is a valid path. Thank you!
