### ISSUE TITLE
Speakar diarization issue

### ISSUE THREAD

**Issue by faisalpathan** [nguyenhuyanhh/nlp_speech#2]
I was using the speaker diarization of the program and it is very good but it repeats the same voice as another speaker all together . So is there any accurate way that even if the waveform of voice of the speaker changes still its says that its the same speaker ?

**Comment by nguyenhuyanhh** [comment]
It's not mine! I used LIUMSpkDiarization - please consult www-lium.univ-lemans.fr/diarization/doku.php. They did say that this tool is best used for broadcast news, for other uses your results might vary.
